version: '3.4'

services:
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:latest"

    networks:
      - stateManagement_net

  ############################
  #Dapr actor placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50005"]
    #ports:
    #  - "50006:50005"
    networks:
      - stateManagement_net

  ############################
  # Dapr zipkin service
  ############################
  zipkin:
    image: "openzipkin/zipkin:latest"
    #command: ["/zipkin","start-zipkin"]
    ports:
      - "9413:9411"
    networks:
      - stateManagement_net

networks:
  stateManagement_net:
  
