version: '3.4'

services:
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    networks:
      - demo_web

  ############################
  #Dapr actor placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50005"]
    #ports:
    #  - "50006:50005"
    networks:
      - demo_web

  ############################
  # Dapr zipkin service
  ############################
  zipkin:
    image: "openzipkin/zipkin:latest"
    #command: ["/zipkin","start-zipkin"]
    ports:
      - "9412:9411"
    networks:
      - demo_web

networks:
  demo_web:
  
